### ISSUE TITLE
Test script fail all

### ISSUE THREAD

**Issue by xuantain** [xuantain/coffeeShopApp#16]
```
PhantomJS 2.0.0 (Linux) Controller: CoffeeshopCtrl should attach a list of coffeeShop to the scope FAILED
        at /media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4139:53
        at forEach (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:323:24)
        at loadModules (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4099:12)
        at createInjector (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4025:22)
        at workFn (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular-mocks/angular-mocks.js:2425:60)
    TypeError: undefined is not an object (evaluating 'scope.coffeeShops') in /media/xuantain/DATA/www/coffeeShopApp/test/spec/controllers/coffeeshop.js (line 42)
        at /media/xuantain/DATA/www/coffeeShopApp/test/spec/controllers/coffeeshop.js:42:17
PhantomJS 2.0.0 (Linux) Controller: CoffeeshopCtrl Test method addNewShop() should add a new shop to coffeeShops when newShop is not exist yet FAILED
        at /media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4139:53
        at forEach (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:323:24)
        at loadModules (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4099:12)
        at createInjector (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4025:22)
        at workFn (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular-mocks/angular-mocks.js:2425:60)
    TypeError: undefined is not an object (evaluating 'scope.coffeeShops') in /media/xuantain/DATA/www/coffeeShopApp/test/spec/controllers/coffeeshop.js (line 49)
        at /media/xuantain/DATA/www/coffeeShopApp/test/spec/controllers/coffeeshop.js:49:25
PhantomJS 2.0.0 (Linux) Controller: CoffeeshopCtrl Test method addNewShop() should add a new shop to coffeeShops when have some shops are similar, but still addNew FAILED
        at /media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4139:53
        at forEach (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:323:24)
        at loadModules (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4099:12)
        at createInjector (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4025:22)
        at workFn (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular-mocks/angular-mocks.js:2425:60)
    TypeError: undefined is not an object (evaluating 'scope.coffeeShops') in /media/xuantain/DATA/www/coffeeShopApp/test/spec/controllers/coffeeshop.js (line 60)
        at /media/xuantain/DATA/www/coffeeShopApp/test/spec/controllers/coffeeshop.js:60:25
PhantomJS 2.0.0 (Linux) Controller: CoffeeshopCtrl Test method addNewShop() should add a new shop to coffeeShops when have some shops are similar, but countinue change shop.titlt and addNew FAILED
        at /media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4139:53
        at forEach (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:323:24)
        at loadModules (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4099:12)
        at createInjector (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4025:22)
        at workFn (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular-mocks/angular-mocks.js:2425:60)
    TypeError: undefined is not an object (evaluating 'scope.coffeeShops') in /media/xuantain/DATA/www/coffeeShopApp/test/spec/controllers/coffeeshop.js (line 72)
        at /media/xuantain/DATA/www/coffeeShopApp/test/spec/controllers/coffeeshop.js:72:25
PhantomJS 2.0.0 (Linux) Controller: CoffeeshopCtrl Test method addNewShop() no new shop added to coffeeShops when scope.shop = {} FAILED
        at /media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4139:53
        at forEach (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:323:24)
        at loadModules (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4099:12)
        at createInjector (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular/angular.js:4025:22)
        at workFn (/media/xuantain/DATA/www/coffeeShopApp/app/bower_components/angular-mocks/angular-mocks.js:2425:60)
    TypeError: undefined is not an object (evaluating 'scope.coffeeShops') in /media/xuantain/DATA/www/coffeeShopApp/test/spec/controllers/coffeeshop.js (line 86)
        at /media/xuantain/DATA/www/coffeeShopApp/test/spec/controllers/coffeeshop.js:86:25
...
```

**Comment by xuantain** [comment]
Hi @cesine , I have some problems, I did not changed configuration in Grunt.js and karma.conf.js but when I try to run test script, it throw errors like above. I tried to fix but it not work, please help me :)

**Comment by xuantain** [comment]
@pnhung177 anh có biết lỗi này bị gì không? Giúp em fix với :D

**Comment by pnhung177** [comment]
I think your problem is here:

https://github.com/xuantain/coffeeShopApp/blob/master/app/scripts/controllers/coffeeshop.js#L132:

var shopsInStore = localStorageService.get('coffeeShops');
    $scope.coffeeShops = shopsInStore || coffeeShopDB.getAll($scope.fetchDataFromDB);

$scope.coffeeShops is set to null.

Please try:

var shopsInStore = localStorageService.get('coffeeShops');
if (!$scope.coffeeShops) {
    $scope.coffeeShops = shopsInStore || coffeeShopDB.getAll($scope.fetchDataFromDB) || [];
}

**Comment by xuantain** [comment]
Reason: declared not enough libraries in karma.conf.js
